"""init_schema_with_timescaledb

Revision ID: 1ba6c9e2b43d
Revises: 
Create Date: 2026-03-02 10:17:52.550570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ba6c9e2b43d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enable TimescaleDB extension (Commented out as user will enable it manually)
    # op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE")

    # Create ENUM types
    op.execute("CREATE TYPE timeframe_enum AS ENUM ('1m', '5m', '15m', '1h', '4h', '1d')")
    op.execute("CREATE TYPE order_side_enum AS ENUM ('buy', 'sell')")
    op.execute("CREATE TYPE order_type_enum AS ENUM ('limit', 'market', 'stop_loss', 'take_profit')")
    op.execute("CREATE TYPE order_status_enum AS ENUM ('open', 'closed', 'canceled', 'failed')")
    op.execute("CREATE TYPE taker_maker_enum AS ENUM ('taker', 'maker')")
    op.execute("CREATE TYPE run_type_enum AS ENUM ('backtest', 'live')")
    op.execute("CREATE TYPE run_status_enum AS ENUM ('running', 'completed', 'failed')")

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'name', name='uix_exchange_name')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=False),
    sa.Column('quote_asset', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exchange_symbol', sa.String(length=50), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('amount_precision', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uix_exchange_symbol')
    )
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('class_path', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('balances',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('free', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('used', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('total', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('time', 'asset')
    )
    op.create_index(op.f('ix_balances_account_id'), 'balances', ['account_id'], unique=False)
    op.create_table('ohlcv',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('time', 'market_id', 'timeframe')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_order_id', sa.String(length=50), nullable=True),
    sa.Column('exchange_order_id', sa.String(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('filled', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('remaining', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cost', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_exchange_order_id'), 'orders', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('positions',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('time', 'market_id')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_created_at'), 'risk_events', ['created_at'], unique=False)
    op.create_table('strategy_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cost', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('taker_or_maker', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('time', 'market_id', 'trade_id')
    )
    op.create_table('executions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('trade_id', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('fee', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('fee_currency', sa.String(length=10), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('taker_or_maker', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_time'), 'executions', ['time'], unique=False)

    # OHLCV 索引
    op.create_index('idx_ohlcv_market_timeframe_time_desc', 'ohlcv', ['market_id', 'timeframe', sa.text('time DESC')])
    op.create_index('idx_ohlcv_market_time_desc', 'ohlcv', ['market_id', sa.text('time DESC')])

    # Trades 索引
    op.create_index('idx_trades_market_time_desc', 'trades', ['market_id', sa.text('time DESC')])

    # Trades 唯一约束 (Removed as it conflicts with TimescaleDB partitioning)
    # op.create_unique_constraint('unique_trades_market_trade_id', 'trades', ['market_id', 'trade_id'])

    # Executions 唯一约束
    op.create_unique_constraint('unique_executions_order_trade_id', 'executions', ['order_id', 'trade_id'])

    # OHLCV Hypertable
    op.execute("SELECT create_hypertable('ohlcv', 'time', if_not_exists => TRUE)")
    
    # Trades Hypertable
    op.execute("SELECT create_hypertable('trades', 'time', if_not_exists => TRUE)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除 Continuous Aggregates
    op.execute("DROP MATERIALIZED VIEW IF EXISTS ohlcv_1h")
    
    # 删除 Hypertable（会自动删除相关策略）
    op.execute("DROP TABLE IF EXISTS trades CASCADE")
    op.execute("DROP TABLE IF EXISTS ohlcv CASCADE")
    
    op.drop_index(op.f('ix_executions_time'), table_name='executions')
    op.drop_table('executions')
    # op.drop_table('trades') # Already dropped
    op.drop_table('strategy_runs')
    op.drop_index(op.f('ix_risk_events_created_at'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_positions_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    # op.drop_table('ohlcv') # Already dropped
    op.drop_index(op.f('ix_balances_account_id'), table_name='balances')
    op.drop_table('balances')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_table('accounts')
    
    # 删除枚举类型
    op.execute("DROP TYPE IF EXISTS run_status_enum")
    op.execute("DROP TYPE IF EXISTS run_type_enum")
    op.execute("DROP TYPE IF EXISTS taker_maker_enum")
    op.execute("DROP TYPE IF EXISTS order_status_enum")
    op.execute("DROP TYPE IF EXISTS order_type_enum")
    op.execute("DROP TYPE IF EXISTS order_side_enum")
    op.execute("DROP TYPE IF EXISTS timeframe_enum")
    # ### end Alembic commands ###
