"""Base strategy class for backtesting.

This module provides the abstract base class that all trading strategies must inherit from.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, Any

from pydantic import BaseModel


class OrderSide(str, Enum):
    """Order side (buy/sell)."""
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    """Order type."""
    MARKET = "market"
    LIMIT = "limit"
    STOP_LOSS = "stop_loss"
    STOP_LIMIT = "stop_limit"


class SignalType(str, Enum):
    """Trading signal type."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    EXIT_LONG = "exit_long"
    EXIT_SHORT = "exit_short"


@dataclass
class OHLCVBar:
    """Single OHLCV bar/candle."""
    time: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    @property
    def typical_price(self) -> float:
        """Typical price (HLC/3)."""
        return (self.high + self.low + self.close) / 3

    @property
    def range(self) -> float:
        """Bar range (high - low)."""
        return self.high - self.low


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    type: SignalType
    symbol: str
    time: datetime
    price: Optional[float] = None  # For limit orders
    quantity: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    metadata: dict = field(default_factory=dict)


@dataclass
class Position:
    """Current position information."""
    symbol: str
    quantity: float
    entry_price: float
    entry_time: datetime
    side: OrderSide
    unrealized_pnl: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None

    @property
    def is_long(self) -> bool:
        return self.side == OrderSide.BUY

    @property
    def is_short(self) -> bool:
        return self.side == OrderSide.SELL

    def update_pnl(self, current_price: float) -> None:
        """Update unrealized PnL based on current price."""
        if self.is_long:
            self.unrealized_pnl = (current_price - self.entry_price) * self.quantity
        else:
            self.unrealized_pnl = (self.entry_price - current_price) * self.quantity


@dataclass
class StrategyState:
    """State container for strategy execution."""
    cash: float
    positions: dict[str, Position] = field(default_factory=dict)
    equity_curve: list[tuple[datetime, float]] = field(default_factory=list)
    trades: list[dict] = field(default_factory=list)
    current_time: Optional[datetime] = None
    current_prices: dict[str, float] = field(default_factory=dict)

    @property
    def position_value(self) -> float:
        """Total value of all positions."""
        return sum(
            pos.quantity * self.current_prices.get(symbol, pos.entry_price)
            for symbol, pos in self.positions.items()
        )

    @property
    def total_equity(self) -> float:
        """Total equity (cash + positions)."""
        return self.cash + self.position_value


class StrategyConfig(BaseModel):
    """Base configuration for strategies."""
    name: str = "BaseStrategy"
    symbols: list[str] = []
    timeframe: str = "1h"
    initial_capital: float = 10000.0

    # Risk management
    max_position_size: float = 0.1  # 10% of equity per position
    max_positions: int = 5
    stop_loss_pct: Optional[float] = None  # e.g., 0.02 for 2%
    take_profit_pct: Optional[float] = None

    # Position sizing
    position_sizing: str = "fixed"  # "fixed", "percent", "kelly"


class BaseStrategy(ABC):
    """Abstract base class for trading strategies.

    All trading strategies must inherit from this class and implement
    the generate_signal method.

    The strategy lifecycle:
    1. init() - Called once before backtesting starts
    2. on_bar() - Called for each bar/candle
    3. generate_signal() - Must be implemented by subclass
    4. on_trade() - Called after a trade is executed
    5. on_finish() - Called once after backtesting ends

    Example:
        class MyStrategy(BaseStrategy):
            def init(self):
                self.sma_period = 20

            def generate_signal(self, bar: OHLCVBar) -> Optional[Signal]:
                if self.indicators["sma"] > bar.close:
                    return Signal(SignalType.BUY, bar.symbol, bar.time)
                return None
    """

    def __init__(self, config: Optional[StrategyConfig] = None):
        self.config = config or StrategyConfig()
        self.state = StrategyState(cash=self.config.initial_capital)
        self.indicators: dict[str, Any] = {}
        self._history: dict[str, list[OHLCVBar]] = {}

    def init(self) -> None:
        """Initialize the strategy.

        Override this method to set up indicators, load historical data, etc.
        Called once before backtesting starts.
        """
        pass

    @abstractmethod
    def generate_signal(self, bar: OHLCVBar, symbol: str) -> Optional[Signal]:
        """Generate a trading signal for the given bar.

        Args:
            bar: Current OHLCV bar
            symbol: Symbol being processed

        Returns:
            Signal if action should be taken, None otherwise
        """
        pass

    def on_bar(self, bar: OHLCVBar, symbol: str) -> Optional[Signal]:
        """Process a new bar and generate a signal.

        Args:
            bar: New OHLCV bar
            symbol: Symbol being processed

        Returns:
            Signal if one is generated
        """
        # Update history
        if symbol not in self._history:
            self._history[symbol] = []
        self._history[symbol].append(bar)

        # Update current price
        self.state.current_time = bar.time
        self.state.current_prices[symbol] = bar.close

        # Update position PnL
        if symbol in self.state.positions:
            self.state.positions[symbol].update_pnl(bar.close)

        # Generate signal
        signal = self.generate_signal(bar, symbol)

        return signal

    def on_trade(self, trade: dict) -> None:
        """Called after a trade is executed.

        Args:
            trade: Trade information dictionary
        """
        self.state.trades.append(trade)

    def on_finish(self) -> None:
        """Called once after backtesting ends.

        Override this method for cleanup, logging, analysis, etc.
        """
        pass

    # Helper methods for strategies

    def get_history(self, symbol: str, length: int = 100) -> list[OHLCVBar]:
        """Get recent historical bars for a symbol.

        Args:
            symbol: Symbol to get history for
            length: Number of bars to return

        Returns:
            List of OHLCV bars
        """
        history = self._history.get(symbol, [])
        return history[-length:] if len(history) > length else history

    def get_close_prices(self, symbol: str, length: int = 100) -> list[float]:
        """Get recent close prices for a symbol.

        Args:
            symbol: Symbol to get prices for
            length: Number of prices to return

        Returns:
            List of close prices
        """
        history = self.get_history(symbol, length)
        return [bar.close for bar in history]

    def get_position(self, symbol: str) -> Optional[Position]:
        """Get current position for a symbol."""
        return self.state.positions.get(symbol)

    def has_position(self, symbol: str) -> bool:
        """Check if there is an open position for a symbol."""
        return symbol in self.state.positions

    def get_equity(self) -> float:
        """Get current total equity."""
        return self.state.total_equity

    def calculate_position_size(
        self,
        price: float,
        symbol: str,
        risk_pct: Optional[float] = None,
    ) -> float:
        """Calculate position size based on configuration.

        Args:
            price: Entry price
            symbol: Symbol to trade
            risk_pct: Optional override for risk percentage

        Returns:
            Position size (quantity)
        """
        equity = self.get_equity()
        sizing = self.config.position_sizing

        if sizing == "fixed":
            # Fixed dollar amount
            amount = equity * self.config.max_position_size
            return amount / price

        elif sizing == "percent":
            # Percent of equity
            pct = risk_pct or self.config.max_position_size
            amount = equity * pct
            return amount / price

        else:
            # Default to fixed
            amount = equity * self.config.max_position_size
            return amount / price